# Build settings
markdown: kramdown

# Site settings
title: "Hi, I'm Christofer Löf"
description: "I'm Building products for Flightradar24, coding the Cloud and explore trails by bike"

email: "christofer@lof.io"
#blog logo
logo: "/assets/images/ChristoferLof_2014.jpg"
# blog cover
cover: "/assets/images/winter_hero.jpg"

name: 'Christofer Löf'
author: 'Christofer Löf'
author_image: "/assets/images/ChristoferLof_2014.jpg"

paginate: 10

url: "https://christofer.lof.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/chrislof
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:
    desc:
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/christoferlof
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:
    desc:
    share_url: https://plus.google.com/share
    share_title: ?t=
    share_link: "&amp;url="
